### PR TITLE
New blog: Introducing Kadalu Kubectl plugin

### PR DESCRIPTION
**Pull request by aravindavk**
Signed-off-by: Aravinda VK <mail@aravindavk.in>

### CODE REVIEW

**Comment by aravindavk** [comment]
Do not merge. Work in progress. Can be published once 0.4 is released.

**Review by amarts — APPROVED** [review]

**Comment by amarts** [comment]
looks good now! let us know if this is good to merge!

**Comment by aravindavk** [comment]
> looks good now! let us know if this is good to merge!

If we are planning a blog post about release-0.4 then this can be published with 2-3 days interval.

**Comment by amarts** [comment]
can the dates be changed, so we can merge it?

**Pull request merged**
