### PR TITLE
New Blog Post Kadalu Storage 0.7

### PR DESCRIPTION
**Pull request by aravindavk**
Signed-off-by: Aravinda Vishwanathapura <aravinda@kadalu.io>

### CODE REVIEW

**Comment by aravindavk** [comment]
Do not merge yet! Release is not Tagged.

**Comment by amarts** [comment]
I guess, after tag we we need to push manifest files? Also I will send a patch to update README.md with how to try ARM support!

**Comment by aravindavk** [comment]
Updated Arm support details(To install from master) and date changed to tomorrow.

**Review by amarts — APPROVED** [review]
So, we are still waiting for py3<->py2 patch! as per this documentation!

**Comment by aravindavk** [comment]
One more point added, which was missing.(Host name removal from Server pod name)

**Pull request merged**
